org: devhamanovich
app: auction
service: auction-service

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  profile: sls
  environment:
    AUCTIONS_TABLE_NAME: ${self:custom.AuctionsTable.name}
    MAIL_QUEUE_URL: ${self:custom.MailQueue.url}
    AUCTIONS_BUCKET_NAME: ${self:custom.AuctionsBucket.name}
    STAGE: ${self:provider.stage}
  iam:
    role:
      statements:
        - ${file(iam/AuctionsTableIAM.yml):AuctionsTableIAM}
        - ${file(iam/MailQueueIAM.yml):MailQueueIAM}
        - ${file(iam/AuctionsBucketIAM.yml):AuctionsBucketIAM}
  httpApi:
    cors: true

resources:
  Resources:
    AuctionsTable: ${file(resources/AuctionsTable.yml):AuctionsTable}
    AuctionsBucket: ${file(resources/AuctionsBucket.yml):AuctionsBucket}
    AuctionsBucketPolicy: ${file(resources/AuctionsBucket.yml):AuctionsBucketPolicy}

functions:
  createAuction:
    handler: handler.createAuction
    events:
      - http:
          path: auction
          method: POST
          authorizer: ${self:custom.authorizer}

  getAuctions:
    handler: handler.getAuctions
    events:
      - http:
          path: auctions
          method: GET
          authorizer: ${self:custom.authorizer}

  getAuction:
    handler: handler.getAuction
    events:
      - http:
          path: auction/{id}
          method: GET
          authorizer: ${self:custom.authorizer}

  placeBid:
    handler: handler.placeBid
    events:
      - http:
          method: PATCH
          path: auction/{id}/bid
          authorizer: ${self:custom.authorizer}
    
  uploadAuctionPicture:
    handler: handler.uploadAuctionPicture
    events:
      - http:
          method: PATCH
          path: auction/{id}/picture
          authorizer: ${self:custom.authorizer}

  processAuctions:
    handler: handler.processAuctions
    # events:
    #   - schedule: rate(1 hour)

custom:
  authorizer: arn:aws:lambda:${aws:region}:${aws:accountId}:function:auth-service-${self:provider.stage}-auth
  AuctionsTable:
    name: !Ref AuctionsTable
    arn: !GetAtt AuctionsTable.Arn
  AuctionsBucket:
    name: auctions-bucket-h2m2kd33ij31ijdon0-${self:provider.stage}
  MailQueue:
    arn: ${cf:notification-service-${self:provider.stage}.MailQueueArn}
    url: ${cf:notification-service-${self:provider.stage}.MailQueueUrl}
