org: devhamanovich
app: auction
service: auth-service

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  profile: sls
  environment:
    AUTH0_PUBLIC_KEY: ${ssm:/auth0-public-key}
    STAGE: ${self:provider.stage}
  httpApi:
    cors: true

resources:
  Resources:
    GatewayResponse: ${file(resources/GatewayResponse.yml):GatewayResponse}
    AuthFailureGatewayResponse: ${file(resources/AuthFailureGatewayResponse.yml):AuthFailureGatewayResponse}

functions:
  auth:
    handler: handler.auth

  publicEndpoint:
    handler: handler.publicEndpoint
    events:
      - http:
          method: POST
          path: public

  privateEndpoint:
    handler: handler.privateEndpoint
    events:
      - http:
          method: POST
          path: private
          authorizer:
            name: auth
